<?php
require("src/Attributes.php");
require("src/FrontController.php");
require("src/EventType.php");
require("src/Application.php");
require("src/Application/Route.php");
require("src/Session/Options.php");
require("src/Cookies/Options.php");
require("src/Request.php");
require("src/Request/Client.php");
require("src/Request/Server.php");
require("src/Request/URI.php");
require("src/Request/UploadedFiles.php");
require("src/Session.php");
require("src/Cookies.php");
require("src/EventListeners/Request.php");
require("src/EventListeners/Validators/RouteValidator.php");
require("src/EventListeners/Validators/FormatValidator.php");
require("src/Controller.php");
